# -*- coding: utf-8 -*-
"""Practical3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxaDvwP7y6ZCpn5i0c6Hyi5XRmCz8gRt

**Import Necessary Libraries**
"""

# Christoph Van Jaarsveld 50143956
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

"""**Generate Data**"""

# Set random seed for reproducibility
np.random.seed(42)
# Number of observations in each cluster - interval of 100 between 100 & 1000
c1 = np.random.randint(1, 11) * 100
c2 = np.random.randint(1, 11) * 100
c3 = np.random.randint(1, 11) * 100

# Total steps per day of each cluster
c1_steps = np.random.randint(8000, 12000, c1)
c2_steps = np.random.randint(5000, 8000, c2)
c3_steps = np.random.randint(2000, 5000, c3)

# Total hours slept per night of each cluster
c1_sleepH = np.random.uniform(7, 9, c1)
c2_sleepH = np.random.uniform(6, 7.5, c2)
c3_sleepH = np.random.uniform(5, 6.5, c3)

# Combine all clusters into a single dataset
x = np.concatenate((c1_steps, c2_steps, c3_steps))
y = np.concatenate((c1_sleepH, c2_sleepH, c3_sleepH))
data = np.column_stack([x, y])

print(f"\nTotal dataset size: {data.shape[0]} users")

"""**Plot Data on Scatter Plot**"""

# Print dataset information
print(f"Total observations in cluster 1: {c1}")
print(f"Total observations in cluster 2: {c2}")
print(f"Total observations in cluster 3: {c3}")

# Create labels for each cluster
labels = np.concatenate((
    np.full(c1, 0),
    np.full(c2, 1),
    np.full(c3, 2)
))

# Define cluster names and colors for the legend
cluster_info = {
    0: {"name": "Active", "color": "#1f77b4"},
    1: {"name": "Moderately active", "color": "#ff7f0e"},
    2: {"name": "Least active", "color": "#2ca02c"}
}

# Create the scatter plot
plt.figure(figsize=(10, 7))

# Iterate through cluster labels 0, 1, 2
for i in sorted(cluster_info.keys()):
    # Select data points for the current cluster
    cluster_x = x[labels == i]
    cluster_y = y[labels == i]
    plt.scatter(cluster_x, cluster_y,
                label=cluster_info[i]["name"],
                color=cluster_info[i]["color"],
                s=50,
                alpha=0.7)

# Add labels and title
plt.xlabel("Steps Per Day")
plt.ylabel("Hours Slept Per Night")
plt.title("Fitness Tracker Data Visualisation")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""**K-Means Clustering**"""

# Number of clusters
n_clusters = 3

# Create a KMeans object with the specified number of clusters
kmeans = KMeans(n_clusters = n_clusters)

# Fit the KMeans model to the data
kmeans.fit(data)

# Get the cluster labels for each data point
kmeans_labels = kmeans.labels_

"""**Cluster Visualusation**"""

plt.figure(figsize=(10, 7))

# Iterate through the KMeans labels (0, 1, 2)
for i in range(n_clusters):
    cluster_points = data[kmeans_labels == i]
    plt.scatter(cluster_points[:,0], cluster_points[:,1],
                s=50,
                alpha=0.7)

plt.xlabel("Steps Per Day")
plt.ylabel("Hours Slept Per Night")
plt.title("KMeans Clustering of Fitness Tracker Data")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""**Cluster Analysis**"""

# Analyse clusters
for i in range(3):

    cluster_points = data[kmeans_labels == i]

    avg_steps = round(np.mean(cluster_points[:,0]), 0) # average steps
    avg_sleep = round(np.mean(cluster_points[:,1]), 1) # average sleep hours

    print(f"\nCentroid {i+1}")
    print(f"Average Steps per Day: {int(avg_steps)}")
    print(f"Average Hours Slept: {avg_sleep}")