# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1djooDzmXx2COZ4PpP8k8n2SGtE5JeN0s
"""

# Christoph Van Jaarsveld 50143956

# Import needed libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Define dataset parameters
# Number of observations in each class
N1 = 100
N2 = 600

# Distance between class centres
d = 2.0

# Standard deviation
sigma1 = 1.0
sigma2 = 1.0

# Generate class center locations
# Class center 1 coordinates
x1_center = d / 2 * np.array([-1, 1])

# Class center 2 coordinates
x2_center = d / 2 * np.array([1, 1])

# Create feature Matrix
# Combine class center locations
X_T = np.vstack((x1_center, x2_center))

# Add noise to class centres to create data points
noise1 = np.random.normal(scale=sigma1, size=(N1, 2))
noise2 = np.random.normal(scale=sigma2, size=(N2, 2))

# Add noise to class cenntres to create data points
X1 = X_T[0, :] + noise1
X2 = X_T[1, :] + noise2

# Combine data points from both classes
X = np.concatenate ((X1, X2), axis=0)

# Generate Class Labels
# Create class labels (0 for class 1, 1 for class 2)
y = np.array([0] * N1 + [1] * N2)

# Visualizse and cluster data
plt.scatter(X[:, 0], X[:, 1], c=y)
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Generated Dataset")
plt.show()

# Define the number of clusters
n_clusters = 2

# Create a KMeans object with the specified number of clusters
kmeans = KMeans(n_clusters=n_clusters)

# Fit the KMeans model to the data
kmeans.fit(X)

# Get the cluster labels assigned by KMeans
kmeans_labels = kmeans.labels_

# Align KMeans labels with true class labels
aligned_labels = np.zeros_like(kmeans_labels)
for cluster in range (n_clusters):
  mask = (kmeans_labels == cluster)
  aligned_labels[mask] = np.argmax(np.bincount(y[mask]))

# Calculate accuracy
accuracy = np.sum(aligned_labels == y) / len(y)
print("Accuracy: ", accuracy)

# Visualise the KMeans clustering results
plt.scatter(X[:, 0], X[:, 1], c=kmeans_labels, cmap='viridis')
plt.scatter(kmeans.cluster_centers_[:, 0],
            kmeans.cluster_centers_[:, 1],
            c='red', s=100, marker='X', label='Centroids') # Mark centroids
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("KMeans Clustering Result")
plt.legend()
plt.show()